spring:
  application:
    name: vacancies-service
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
